### ISSUE TITLE
Amp plugin module closure incorrectly configured

### ISSUE THREAD

**Issue by RVanhuysseXenit** [xenit-eu/alfresco-gradle-sdk#32]
Given config:
```
sourceSets {
        main {
            amp {
                module {
                    def aliasesString = 'care4alf'
                    if (project.name.contains('6x')) {
                        aliasesString += ', eu.xenit.care4alf-5x'
                    }
                    put("module.aliases", aliasesString)
                }
                dynamicExtension()
            }
        }
    }

```

Observed behaviour:

```
* What went wrong:

Could not determine the dependencies of task ':c4a-impl:care4alf-5x:amp'.

> Could not create task ':c4a-impl:care4alf-5x:processModuleProperties'.

   > Could not find method put() for arguments [module.aliases, care4alf] on object of type eu.xenit.gradle.alfrescosdk.internal.tasks.DefaultAmpSourceSetConfiguration.
```

Workaround: use implicit parameter
```
sourceSets {
        main {
            amp {
                module {
                    def aliasesString = 'care4alf'
                    if (project.name.contains('6x')) {
                        aliasesString += ', eu.xenit.care4alf-5x'
                    }
                    it.put("module.aliases", aliasesString)
                }
                dynamicExtension()
            }
        }
    }

```

**Comment by vierbergenlars** [comment]
This can't really be fixed without losing access to variables outside the map.

Currently, the delegate of the closure is incorrectly set. While fixing that is possible, it breaks a lot of usages.

Resolving a variable inside the closure goes through the [`BeanDynamicObject`](https://github.com/gradle/gradle/blob/c9c5259fecc10e6c8f1762e0c45bdda296d3af52/subprojects/model-core/src/main/java/org/gradle/internal/metaobject/BeanDynamicObject.java#L113-L114) class. It uses a separate [adapter implementation](https://github.com/gradle/gradle/blob/c9c5259fecc10e6c8f1762e0c45bdda296d3af52/subprojects/model-core/src/main/java/org/gradle/internal/metaobject/BeanDynamicObject.java#L600-L623) to handle `Map`s, where any property that does not exist on `Map` directly is delegated to `Map#get(Object key)`. The `get` method returns `null` for keys that do not exist. For Groovy, this is not the same as the property not existing, but it mean the property exists and it's value is `null`.

This will make constructs like https://github.com/xenit-eu/alfresco-gradle-sdk/blob/master/src/integrationTest/resources/examples/multi-source-alfresco-project/build.gradle#L19-L22 impossible to implement, because the `project` variable will be `null` here.
